import argparse
import json
import math
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")

import lightgbm as lgb
import numpy as np
import pandas as pd

from .compare_entry_twostage_forecasts import (
    build_supervised_frame,
    choose_fit_calibration_windows,
    feature_columns,
    make_features_for_target,
)
from .compare_stage_forecasts import build_delay_kernel, load_split, resolve_window_ms
from .compare_stage_rolling_forecasts import window_series
from ..workflow import load_workflow


POLICIES = {"p50": 0.50, "p90": 0.90, "p95": 0.95}


@dataclass
class QuantileModelSet:
    models: dict[str, object]
    fallback_quantiles: dict[str, float]
    shifts: dict[str, float]
    features: list[str]
    calibration_mode: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Rolling-origin Quantile LightGBM forecast for workflow entry arrivals, "
            "DAG-propagated stage arrivals, and per-stage independent baselines."
        )
    )
    parser.add_argument("--trace", required=True)
    parser.add_argument("--workflow-config", required=True)
    parser.add_argument(
        "--split-index",
        required=True,
        help="rolling index CSV generated by make_rolling_time_splits.py",
    )
    parser.add_argument("--window-sec", type=int, default=5)
    parser.add_argument("--window-ms", type=int, default=None)
    parser.add_argument("--activation-threshold", type=float, default=0.1)
    parser.add_argument(
        "--calibration-modes",
        default="none,conformal",
        help="comma-separated modes: none,conformal",
    )
    parser.add_argument("--calibration-fraction", type=float, default=0.25)
    parser.add_argument("--min-train-rows", type=int, default=30)
    parser.add_argument("--n-estimators", type=int, default=160)
    parser.add_argument("--learning-rate", type=float, default=0.04)
    parser.add_argument("--num-leaves", type=int, default=15)
    parser.add_argument("--min-child-samples", type=int, default=12)
    parser.add_argument("--subsample", type=float, default=1.0)
    parser.add_argument("--colsample-bytree", type=float, default=1.0)
    parser.add_argument("--n-jobs", type=int, default=1)
    parser.add_argument("--random-state", type=int, default=42)
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--write-forecast-csvs", action="store_true")
    return parser.parse_args()


def project_root() -> Path:
    return Path(__file__).resolve().parent.parent.parent


def resolve_path(root: Path, maybe_relative: str) -> Path:
    path = Path(maybe_relative)
    return path if path.is_absolute() else root / path


def ceil_count(value: float) -> int:
    return int(math.ceil(max(0.0, float(value))))


def alloc_count(value: float, activation_threshold: float) -> int:
    value = max(0.0, float(value))
    if value < activation_threshold:
        return 0
    return ceil_count(value)


def pinball_loss(actual: float, forecast: float, quantile: float) -> float:
    error = float(actual) - float(forecast)
    return max(quantile * error, (quantile - 1.0) * error)


def method_name(prefix: str, calibration_mode: str) -> str:
    if calibration_mode == "none":
        return f"{prefix}-lightgbm-quantile"
    return f"{prefix}-lightgbm-quantile-{calibration_mode}"


def fit_single_quantile_model(
    train: pd.DataFrame,
    features: list[str],
    policy: str,
    quantile: float,
    args: argparse.Namespace,
) -> object | None:
    y = train["target_count"].astype(float).to_numpy()
    if len(train) < args.min_train_rows or len(np.unique(y)) < 2:
        return None
    model = lgb.LGBMRegressor(
        objective="quantile",
        alpha=quantile,
        n_estimators=args.n_estimators,
        learning_rate=args.learning_rate,
        num_leaves=args.num_leaves,
        min_child_samples=args.min_child_samples,
        subsample=args.subsample,
        colsample_bytree=args.colsample_bytree,
        random_state=args.random_state + int(quantile * 1000),
        n_jobs=args.n_jobs,
        verbosity=-1,
        force_col_wise=True,
    )
    model.fit(train[features], y)
    return model


def predict_model_set(model_set: QuantileModelSet, frame: pd.DataFrame) -> pd.DataFrame:
    out = frame[["window"]].copy()
    previous = None
    for policy, quantile in POLICIES.items():
        model = model_set.models.get(policy)
        if model is None:
            pred = np.full(len(frame), model_set.fallback_quantiles[policy], dtype=float)
        else:
            pred = np.asarray(model.predict(frame[model_set.features]), dtype=float)
        pred = np.maximum(0.0, pred + model_set.shifts.get(policy, 0.0))
        if previous is not None:
            pred = np.maximum(previous, pred)
        out[f"{policy}_count"] = pred
        previous = pred
    for policy in POLICIES:
        out[f"ceil_{policy}_count"] = out[f"{policy}_count"].map(ceil_count)
    return out


def fit_model_set(
    counts: pd.Series,
    first_window: int,
    train_end_window: int,
    window_ms: int,
    calibration_mode: str,
    args: argparse.Namespace,
) -> QuantileModelSet:
    train = build_supervised_frame(
        counts,
        first_window + 1,
        train_end_window,
        first_window,
        window_ms,
    )
    if train.empty:
        train = pd.DataFrame(
            [make_features_for_target(counts, train_end_window, first_window, window_ms)]
        )
        train["window"] = train_end_window
        train["target_count"] = float(counts.get(train_end_window, 0.0))
        train["target_active"] = 1 if train["target_count"].iloc[0] > 0 else 0
    features = feature_columns(train)

    if calibration_mode == "conformal" and len(train) >= max(12, args.min_train_rows):
        train_windows = train["window"].to_numpy(dtype=int)
        fit_end, cal_start = choose_fit_calibration_windows(
            train_windows,
            args.calibration_fraction,
        )
        fit_frame = train[train["window"] <= fit_end].copy()
        cal_frame = train[train["window"] >= cal_start].copy()
        if fit_frame.empty or cal_frame.empty:
            fit_frame = train.copy()
            cal_frame = pd.DataFrame()
    else:
        fit_frame = train.copy()
        cal_frame = pd.DataFrame()

    fallback_quantiles = {
        policy: float(fit_frame["target_count"].quantile(quantile))
        for policy, quantile in POLICIES.items()
    }
    models = {
        policy: fit_single_quantile_model(fit_frame, features, policy, quantile, args)
        for policy, quantile in POLICIES.items()
    }
    shifts = {policy: 0.0 for policy in POLICIES}
    model_set = QuantileModelSet(
        models=models,
        fallback_quantiles=fallback_quantiles,
        shifts=shifts,
        features=features,
        calibration_mode=calibration_mode,
    )

    if calibration_mode == "conformal" and not cal_frame.empty:
        cal_pred = predict_model_set(model_set, cal_frame)
        for policy, quantile in POLICIES.items():
            residual = (
                cal_frame["target_count"].astype(float).to_numpy()
                - cal_pred[f"{policy}_count"].astype(float).to_numpy()
            )
            shifts[policy] = float(np.quantile(residual, quantile))
        model_set.shifts = shifts

    return model_set


def build_eval_frame(
    counts: pd.Series,
    target_windows: list[int],
    first_window: int,
    window_ms: int,
) -> pd.DataFrame:
    rows = []
    for target_window in target_windows:
        row = make_features_for_target(counts, target_window, first_window, window_ms)
        row["window"] = int(target_window)
        row["target_count"] = float(counts.get(target_window, 0.0))
        row["target_active"] = 1 if row["target_count"] > 0 else 0
        rows.append(row)
    return pd.DataFrame(rows)


def count_series_from_windows(
    rows: pd.DataFrame,
    window_col: str,
    first_window: int,
    last_window: int,
) -> pd.Series:
    if rows.empty:
        return pd.Series(0.0, index=range(first_window, last_window + 1), dtype=float)
    return (
        rows.groupby(window_col)
        .size()
        .reindex(range(first_window, last_window + 1), fill_value=0)
        .astype(float)
    )


def build_entry_forecasts_for_fold(
    entries: pd.DataFrame,
    workflow_name: str,
    first_window: int,
    train_end_window: int,
    eval_windows: list[int],
    window_ms: int,
    calibration_modes: list[str],
    args: argparse.Namespace,
) -> list[pd.DataFrame]:
    last_needed = max(max(eval_windows), train_end_window)
    counts = count_series_from_windows(entries, "window", first_window, last_needed)
    eval_frame = build_eval_frame(counts, eval_windows, first_window, window_ms)
    outputs = []
    for calibration_mode in calibration_modes:
        model_set = fit_model_set(
            counts,
            first_window,
            train_end_window,
            window_ms,
            calibration_mode,
            args,
        )
        forecast = predict_model_set(model_set, eval_frame)
        forecast["workflow_name"] = workflow_name
        forecast["method"] = method_name("entry", calibration_mode)
        forecast["window_start_ms"] = forecast["window"] * window_ms
        for policy in POLICIES:
            forecast[f"alloc_{policy}_count"] = forecast[f"{policy}_count"].map(
                lambda value: alloc_count(value, args.activation_threshold)
            )
        outputs.append(forecast)
    return outputs


def propagate_entry_forecast(
    workflow_name: str,
    workflow,
    entry_forecast: pd.DataFrame,
    train_stage_rows: pd.DataFrame,
    window_ms: int,
    calibration_mode: str,
    activation_threshold: float,
) -> pd.DataFrame:
    rows = []
    for stage_name in workflow.nodes:
        stage_rows = train_stage_rows[train_stage_rows["stage_name"] == stage_name].copy()
        kernel = build_delay_kernel(stage_rows, window_ms) if not stage_rows.empty else {0: 1.0}
        for _, forecast_row in entry_forecast.iterrows():
            for offset, probability in kernel.items():
                target_window = int(forecast_row["window"]) + int(offset)
                row = {
                    "workflow_name": workflow_name,
                    "method": method_name("dag", calibration_mode),
                    "stage_name": stage_name,
                    "window": target_window,
                    "window_start_ms": target_window * window_ms,
                }
                for policy in POLICIES:
                    row[f"{policy}_count"] = float(forecast_row[f"{policy}_count"]) * float(
                        probability
                    )
                rows.append(row)
    if not rows:
        return pd.DataFrame()
    out = (
        pd.DataFrame(rows)
        .groupby(["workflow_name", "method", "stage_name", "window", "window_start_ms"], as_index=False)[
            [f"{policy}_count" for policy in POLICIES]
        ]
        .sum()
    )
    for policy in POLICIES:
        out[f"ceil_{policy}_count"] = out[f"{policy}_count"].map(ceil_count)
        out[f"alloc_{policy}_count"] = out[f"{policy}_count"].map(
            lambda value: alloc_count(value, activation_threshold)
        )
    return out


def build_independent_stage_forecasts_for_fold(
    stage_rows: pd.DataFrame,
    workflow,
    workflow_name: str,
    first_window: int,
    train_end_window: int,
    eval_windows: list[int],
    window_ms: int,
    calibration_modes: list[str],
    args: argparse.Namespace,
) -> list[pd.DataFrame]:
    outputs = {mode: [] for mode in calibration_modes}
    last_needed = max(max(eval_windows), train_end_window)
    for stage_name in workflow.nodes:
        stage = stage_rows[stage_rows["stage_name"] == stage_name].copy()
        counts = count_series_from_windows(stage, "dispatch_window", first_window, last_needed)
        eval_frame = build_eval_frame(counts, eval_windows, first_window, window_ms)
        for calibration_mode in calibration_modes:
            model_set = fit_model_set(
                counts,
                first_window,
                train_end_window,
                window_ms,
                calibration_mode,
                args,
            )
            forecast = predict_model_set(model_set, eval_frame)
            forecast["workflow_name"] = workflow_name
            forecast["method"] = method_name("independent", calibration_mode)
            forecast["stage_name"] = stage_name
            forecast["window_start_ms"] = forecast["window"] * window_ms
            for policy in POLICIES:
                forecast[f"alloc_{policy}_count"] = forecast[f"{policy}_count"].map(
                    lambda value: alloc_count(value, args.activation_threshold)
                )
            outputs[calibration_mode].append(forecast)
    return [pd.concat(parts, ignore_index=True) for parts in outputs.values() if parts]


def actual_entry_counts(entries: pd.DataFrame, eval_windows: list[int]) -> dict[int, int]:
    counts = entries.groupby("window").size()
    return {int(window): int(counts.get(window, 0)) for window in eval_windows}


def actual_stage_counts(
    test_stage_rows: pd.DataFrame,
    stages: list[str],
    eval_windows: list[int],
) -> dict[tuple[str, int], int]:
    counts = test_stage_rows.groupby(["stage_name", "dispatch_window"]).size()
    out = {}
    for stage in stages:
        for window in eval_windows:
            out[(stage, int(window))] = int(counts.get((stage, int(window)), 0))
    return out


def complete_stage_forecast(
    forecast: pd.DataFrame,
    workflow,
    workflow_name: str,
    method: str,
    eval_windows: list[int],
    window_ms: int,
) -> pd.DataFrame:
    grid = pd.MultiIndex.from_product(
        [list(workflow.nodes), eval_windows],
        names=["stage_name", "window"],
    ).to_frame(index=False)
    grid["workflow_name"] = workflow_name
    grid["method"] = method
    grid["window_start_ms"] = grid["window"] * window_ms
    value_cols = []
    for policy in POLICIES:
        value_cols.extend([f"{policy}_count", f"ceil_{policy}_count", f"alloc_{policy}_count"])
    use = forecast[["stage_name", "window"] + [col for col in value_cols if col in forecast]].copy()
    use = use.groupby(["stage_name", "window"], as_index=False).max(numeric_only=True)
    completed = grid.merge(use, on=["stage_name", "window"], how="left")
    for col in value_cols:
        if col not in completed:
            completed[col] = 0.0
        completed[col] = completed[col].fillna(0.0)
    return completed


def detail_from_forecast(
    forecast: pd.DataFrame,
    actual: dict,
    fold_id: int,
    workflow_name: str,
    method_family: str,
    level: str,
    window_ms: int,
) -> pd.DataFrame:
    rows = []
    for _, row in forecast.iterrows():
        for policy, quantile in POLICIES.items():
            if level == "entry":
                actual_count = int(actual.get(int(row["window"]), 0))
                stage_name = "__entry__"
            else:
                stage_name = str(row["stage_name"])
                actual_count = int(actual.get((stage_name, int(row["window"])), 0))
            forecast_count = float(row[f"{policy}_count"])
            allocated_count = int(row.get(f"alloc_{policy}_count", ceil_count(forecast_count)))
            under_count = max(0, actual_count - allocated_count)
            over_count = max(0, allocated_count - actual_count)
            rows.append(
                {
                    "fold_id": int(fold_id),
                    "workflow_name": workflow_name,
                    "method_family": method_family,
                    "method": str(row["method"]),
                    "policy": policy,
                    "nominal_quantile": quantile,
                    "stage_name": stage_name,
                    "origin_window": int(row["window"]) - 1,
                    "target_window": int(row["window"]),
                    "horizon_step": 1,
                    "actual_count": actual_count,
                    "forecast_count": forecast_count,
                    "allocated_count": allocated_count,
                    "under_count": under_count,
                    "over_count": over_count,
                    "quantile_hit": actual_count <= forecast_count,
                    "pinball_loss": pinball_loss(actual_count, forecast_count, quantile),
                    "window_ms": int(window_ms),
                }
            )
    return pd.DataFrame(rows)


def summarize_detail(detail: pd.DataFrame, by_stage: bool = False) -> pd.DataFrame:
    group_cols = ["workflow_name", "method_family", "method", "policy", "nominal_quantile"]
    if by_stage:
        group_cols.append("stage_name")
    rows = []
    for keys, group in detail.groupby(group_cols):
        if not isinstance(keys, tuple):
            keys = (keys,)
        actual = group["actual_count"].astype(float)
        forecast = group["forecast_count"].astype(float)
        allocated = group["allocated_count"].astype(float)
        active = group[group["actual_count"] > 0]
        actual_total = float(actual.sum())
        allocated_total = float(allocated.sum())
        under_total = float(group["under_count"].sum())
        over_total = float(group["over_count"].sum())
        empirical_coverage = float(group["quantile_hit"].mean()) if len(group) else 1.0
        active_empirical_coverage = (
            float(active["quantile_hit"].mean()) if len(active) else 1.0
        )
        nominal = float(group["nominal_quantile"].iloc[0])
        row = {
            **dict(zip(group_cols, keys)),
            "folds": int(group["fold_id"].nunique()),
            "origins": int(group["origin_window"].nunique()),
            "forecast_rows": int(len(group)),
            "active_rows": int(len(active)),
            "actual_total": int(actual_total),
            "allocated_replica_windows": int(allocated_total),
            "allocated_replica_seconds": float(
                allocated_total * float(group["window_ms"].iloc[0]) / 1000.0
            ),
            "under_total": int(under_total),
            "over_total": int(over_total),
            "coverage_rate": float((group["under_count"] == 0).mean()),
            "active_coverage_rate": (
                float((active["under_count"] == 0).mean()) if len(active) else 1.0
            ),
            "demand_coverage_rate": (
                float(1.0 - under_total / actual_total) if actual_total > 0 else 1.0
            ),
            "allocation_utilization": (
                float((actual_total - under_total) / allocated_total)
                if allocated_total > 0
                else 0.0
            ),
            "over_allocation_ratio": (
                float(over_total / allocated_total) if allocated_total > 0 else 0.0
            ),
            "mae": float(np.mean(np.abs(actual - forecast))),
            "rmse": float(np.sqrt(np.mean((actual - forecast) ** 2))),
            "pinball_loss_mean": float(group["pinball_loss"].mean()),
            "active_pinball_loss_mean": (
                float(active["pinball_loss"].mean()) if len(active) else 0.0
            ),
            "empirical_quantile_coverage": empirical_coverage,
            "active_empirical_quantile_coverage": active_empirical_coverage,
            "quantile_calibration_error": abs(empirical_coverage - nominal),
            "active_quantile_calibration_error": abs(active_empirical_coverage - nominal),
            "mean_forecast_count": float(forecast.mean()),
            "max_actual": int(actual.max()) if len(actual) else 0,
            "max_allocated": int(allocated.max()) if len(allocated) else 0,
        }
        rows.append(row)
    return pd.DataFrame(rows)


def write_report(out_dir: Path, entry_summary: pd.DataFrame, stage_summary: pd.DataFrame) -> None:
    def compact(frame: pd.DataFrame) -> pd.DataFrame:
        cols = [
            "method_family",
            "method",
            "policy",
            "demand_coverage_rate",
            "allocated_replica_seconds",
            "over_allocation_ratio",
            "pinball_loss_mean",
            "empirical_quantile_coverage",
            "quantile_calibration_error",
        ]
        return frame[[col for col in cols if col in frame.columns]].copy()

    lines = [
        "# Quantile LightGBM Rolling Forecast Report",
        "",
        "## Scope",
        "",
        "- Forecast policies: `p50`, `p90`, `p95`.",
        "- Models: Quantile LightGBM, with raw and conformal-shift variants.",
        "- Stage methods: workflow-entry forecast with DAG propagation, and per-stage independent baseline.",
        "- Evaluation: rolling-origin folds from the provided split index.",
        "",
        "## Entry Summary",
        "",
        compact(entry_summary).to_markdown(index=False),
        "",
        "## Stage Summary",
        "",
        compact(stage_summary).to_markdown(index=False),
        "",
        "## Notes",
        "",
        "- `empirical_quantile_coverage` checks whether actual demand is below the predicted quantile.",
        "- `quantile_calibration_error = |empirical coverage - nominal quantile|`.",
        "- `demand_coverage_rate` uses allocated integer counts after activation threshold and ceiling.",
        "",
    ]
    (out_dir / "README.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()

    root = project_root()
    trace_path = resolve_path(root, args.trace)
    workflow_path = resolve_path(root, args.workflow_config)
    split_index_path = resolve_path(root, args.split_index)
    out_dir = resolve_path(root, args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    window_ms = resolve_window_ms(args)
    workflow = load_workflow(str(workflow_path))
    workflow_name = workflow.workflow_name
    trace = pd.read_csv(trace_path)
    split_index = pd.read_csv(split_index_path)
    calibration_modes = [
        item.strip()
        for item in args.calibration_modes.split(",")
        if item.strip()
    ]
    for mode in calibration_modes:
        if mode not in {"none", "conformal"}:
            raise ValueError(f"unsupported calibration mode: {mode}")

    workflow_rows = trace[
        (trace["workflow_name"] == workflow_name)
        & (trace["status"] == "ok")
    ].copy()
    entries = workflow_rows[workflow_rows["stage_name"] == "__entry__"].copy()
    entries["window"] = window_series(entries, "entry_ts_ms", window_ms)
    first_entry_window = int(entries["window"].min())

    stage_rows = workflow_rows[workflow_rows["stage_name"] != "__entry__"].copy()
    stage_rows["dispatch_window"] = window_series(stage_rows, "dispatch_start_ms", window_ms)
    first_stage_window = int(stage_rows["dispatch_window"].min())

    entry_detail_frames = []
    stage_detail_frames = []
    forecast_frames = []

    for _, fold in split_index.iterrows():
        fold_id = int(fold["fold_id"])
        split_path = Path(str(fold["split_path"]))
        if not split_path.is_absolute():
            split_path = resolve_path(root, str(split_path))
        train_ids, test_ids, split_map = load_split(
            trace,
            workflow_name,
            str(split_path),
            train_ratio=0.7,
            split_strategy="time",
        )
        split_map["entry_window"] = (split_map["entry_ts_ms"] // window_ms).astype(int)
        train_end_window = int(pd.to_numeric(split_map["split_cutoff_ms"]).dropna().iloc[0] // window_ms)

        test_entries = entries[entries["request_id"].isin(test_ids)].copy()
        if test_entries.empty:
            continue
        entry_eval_windows = list(
            range(int(test_entries["window"].min()), int(test_entries["window"].max()) + 1)
        )
        entry_actual = actual_entry_counts(test_entries, entry_eval_windows)

        entry_forecasts = build_entry_forecasts_for_fold(
            entries=entries,
            workflow_name=workflow_name,
            first_window=first_entry_window,
            train_end_window=train_end_window,
            eval_windows=entry_eval_windows,
            window_ms=window_ms,
            calibration_modes=calibration_modes,
            args=args,
        )
        for entry_forecast in entry_forecasts:
            mode = (
                "conformal"
                if str(entry_forecast["method"].iloc[0]).endswith("-conformal")
                else "none"
            )
            entry_detail_frames.append(
                detail_from_forecast(
                    entry_forecast,
                    entry_actual,
                    fold_id,
                    workflow_name,
                    "entry-lightgbm",
                    "entry",
                    window_ms,
                )
            )
            train_stage_rows = stage_rows[stage_rows["dispatch_window"] <= train_end_window].copy()
            dag_forecast = propagate_entry_forecast(
                workflow_name=workflow_name,
                workflow=workflow,
                entry_forecast=entry_forecast,
                train_stage_rows=train_stage_rows,
                window_ms=window_ms,
                calibration_mode=mode,
                activation_threshold=args.activation_threshold,
            )
            forecast_frames.append(dag_forecast.assign(fold_id=fold_id))

        test_stage_rows = stage_rows[stage_rows["request_id"].isin(test_ids)].copy()
        if test_stage_rows.empty:
            continue
        stage_eval_windows = list(
            range(
                int(test_stage_rows["dispatch_window"].min()),
                int(test_stage_rows["dispatch_window"].max()) + 1,
            )
        )
        stage_actual = actual_stage_counts(test_stage_rows, list(workflow.nodes), stage_eval_windows)

        for forecast in forecast_frames[-len(entry_forecasts) :]:
            completed = complete_stage_forecast(
                forecast,
                workflow,
                workflow_name,
                str(forecast["method"].iloc[0]),
                stage_eval_windows,
                window_ms,
            )
            stage_detail_frames.append(
                detail_from_forecast(
                    completed,
                    stage_actual,
                    fold_id,
                    workflow_name,
                    "entry-lightgbm-dag",
                    "stage",
                    window_ms,
                )
            )

        independent_forecasts = build_independent_stage_forecasts_for_fold(
            stage_rows=stage_rows,
            workflow=workflow,
            workflow_name=workflow_name,
            first_window=first_stage_window,
            train_end_window=train_end_window,
            eval_windows=stage_eval_windows,
            window_ms=window_ms,
            calibration_modes=calibration_modes,
            args=args,
        )
        for forecast in independent_forecasts:
            forecast_frames.append(forecast.assign(fold_id=fold_id))
            completed = complete_stage_forecast(
                forecast,
                workflow,
                workflow_name,
                str(forecast["method"].iloc[0]),
                stage_eval_windows,
                window_ms,
            )
            stage_detail_frames.append(
                detail_from_forecast(
                    completed,
                    stage_actual,
                    fold_id,
                    workflow_name,
                    "per-stage-independent-lightgbm",
                    "stage",
                    window_ms,
                )
            )

    entry_detail = pd.concat(entry_detail_frames, ignore_index=True)
    stage_detail = pd.concat(stage_detail_frames, ignore_index=True)
    entry_summary = summarize_detail(entry_detail, by_stage=False)
    stage_summary = summarize_detail(stage_detail, by_stage=False)
    stage_by_stage = summarize_detail(stage_detail, by_stage=True)

    entry_detail.to_csv(out_dir / "entry_detail.csv", index=False)
    entry_summary.to_csv(out_dir / "entry_summary.csv", index=False)
    stage_detail.to_csv(out_dir / "stage_detail.csv", index=False)
    stage_summary.to_csv(out_dir / "stage_summary.csv", index=False)
    stage_by_stage.to_csv(out_dir / "stage_by_stage.csv", index=False)
    if args.write_forecast_csvs and forecast_frames:
        pd.concat(forecast_frames, ignore_index=True).to_csv(out_dir / "forecasts.csv", index=False)

    metadata = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "trace": str(trace_path),
        "workflow_config": str(workflow_path),
        "split_index": str(split_index_path),
        "workflow_name": workflow_name,
        "window_ms": window_ms,
        "calibration_modes": calibration_modes,
        "policies": POLICIES,
        "lightgbm_version": lgb.__version__,
        "args": vars(args),
    }
    (out_dir / "metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    write_report(out_dir, entry_summary, stage_summary)

    print(f"wrote {out_dir}")
    print("entry summary:")
    print(entry_summary.to_string(index=False))
    print("stage summary:")
    print(stage_summary.to_string(index=False))


if __name__ == "__main__":
    main()

