workflow_name: linear3
namespace: guest
entry: decode
nodes:
  - name: decode
    action: wf_decode
    parents: []
    sleep_ms: 20
  - name: resize
    action: wf_resize
    parents: [decode]
    sleep_ms: 35
  - name: classify
    action: wf_classify
    parents: [resize]
    sleep_ms: 45

